# Generated by Django 3.2.3 on 2021-11-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='klub',
            field=models.TextField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='licencja',
            field=models.TextField(blank=True, max_length=60, null=True, verbose_name='Numer licencji'),
        ),
    ]
