# Generated by Django 3.2.9 on 2021-11-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_rts_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='rts',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Rts',
        ),
    ]
