# Generated by Django 3.2.9 on 2022-01-05 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20211125_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='paid',
        ),
    ]
