# Generated by Django 3.2.9 on 2022-01-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_account_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='klasa_sedziego',
            field=models.TextField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='licencja_sedziego',
            field=models.TextField(blank=True, max_length=60, null=True, verbose_name='Numer licencji sędziego'),
        ),
        migrations.AlterField(
            model_name='account',
            name='klub',
            field=models.TextField(blank=True, max_length=60, null=True, verbose_name='Klasa sędziego'),
        ),
    ]
