# Generated by Django 3.2.9 on 2022-02-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_account_is_sedzia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='klasa_sedziego',
            field=models.TextField(blank=True, max_length=60, null=True, verbose_name='Klasa sędziego'),
        ),
        migrations.AlterField(
            model_name='account',
            name='klub',
            field=models.TextField(blank=True, max_length=60, null=True),
        ),
    ]
