# Generated by Django 4.0.1 on 2022-04-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20220223_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='rodo_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
