# Generated by Django 3.2.6 on 2021-10-01 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zawody', '0001_initial'),
        ('wyniki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wyniki',
            name='wynik1',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='wyniki',
            name='zawody',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zawody.zawody'),
        ),
    ]
