# Generated by Django 3.2.3 on 2021-10-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wyniki', '0002_auto_20211001_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wyniki',
            old_name='wynik1',
            new_name='X',
        ),
        migrations.AddField(
            model_name='wyniki',
            name='Xx',
            field=models.IntegerField(blank=True, default=0, verbose_name='/'),
        ),
        migrations.AddField(
            model_name='wyniki',
            name='cztery',
            field=models.IntegerField(blank=True, default=0, verbose_name='4'),
        ),
        migrations.AddField(
            model_name='wyniki',
            name='dwa',
            field=models.IntegerField(blank=True, default=0, verbose_name='2'),
        ),
        migrations.AddField(
            model_name='wyniki',
            name='dziewiec',
            field=models.IntegerField(blank=True, default=0, verbose_name='9'),
        ),
        migrations.AddField(
            model_name='wyniki',
            name='jeden',
            field=models.IntegerField(blank=True, default=0, verbose_name='1'),
        ),
        migrations.AddField(
            model_name='wyniki',
            name='osiem',
            field=models.IntegerField(blank=True, default=0, verbose_name='8'),
        ),
        migrations.AddField(
            model_name='wyniki',
            name='piec',
            field=models.IntegerField(blank=True, default=0, verbose_name='5'),
        ),
        migrations.AddField(
            model_name='wyniki',
            name='siedem',
            field=models.IntegerField(blank=True, default=0, verbose_name='7'),
        ),
        migrations.AddField(
            model_name='wyniki',
            name='szesc',
            field=models.IntegerField(blank=True, default=0, verbose_name='6'),
        ),
        migrations.AddField(
            model_name='wyniki',
            name='trzy',
            field=models.IntegerField(blank=True, default=0, verbose_name='3'),
        ),
        migrations.AddField(
            model_name='wyniki',
            name='wynik',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
