# Generated by Django 3.2.3 on 2021-10-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wyniki', '0003_auto_20211002_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='wyniki',
            name='komunikat',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
