# Generated by Django 3.2.3 on 2021-10-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wyniki', '0004_wyniki_komunikat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ustawienia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.TextField()),
                ('ustawienie', models.BooleanField(verbose_name='On/Off')),
            ],
            options={
                'verbose_name_plural': 'Ustawienia',
            },
        ),
    ]
