# Generated by Django 3.2.9 on 2022-01-05 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zawody', '0008_alter_turniej_rejestracja'),
        ('wyniki', '0007_alter_wyniki_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wyniki',
            name='zawody',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zawody.zawody', verbose_name='konkurencja'),
        ),
    ]
