# Generated by Django 3.2.9 on 2022-01-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wyniki', '0008_alter_wyniki_zawody'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wyniki',
            name='komunikat',
        ),
        migrations.AddField(
            model_name='wyniki',
            name='oplata',
            field=models.BooleanField(default=False),
        ),
    ]
