# Generated by Django 3.2.9 on 2022-01-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wyniki', '0011_alter_wyniki_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='wyniki',
            name='kara',
            field=models.CharField(choices=[('DNF', 'DNF'), ('DNS', 'DNS'), ('DSQ', 'DSQ'), ('PK', 'PK')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='wyniki',
            name='Xx',
            field=models.IntegerField(blank=True, default=0, verbose_name='10'),
        ),
    ]
