# Generated by Django 3.2.9 on 2022-01-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wyniki', '0013_alter_wyniki_kara'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wyniki',
            name='kara',
            field=models.CharField(choices=[('BRAK', 'BRAK'), ('DNF', 'DNF'), ('DNS', 'DNS'), ('DSQ', 'DSQ'), ('PK', 'PK')], default='BRAK', max_length=10),
        ),
    ]
