# Generated by Django 3.2.9 on 2022-02-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wyniki', '0014_alter_wyniki_kara'),
    ]

    operations = [
        migrations.AddField(
            model_name='wyniki',
            name='amunicja_klubowa',
            field=models.BooleanField(default=False, verbose_name='Amunicja klubowa'),
        ),
        migrations.AddField(
            model_name='wyniki',
            name='bron_klubowa',
            field=models.BooleanField(default=False, verbose_name='Broń klubowa'),
        ),
        migrations.AddField(
            model_name='wyniki',
            name='edited_by_sedzia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wyniki',
            name='kara_punktowa',
            field=models.IntegerField(blank=True, default=0, verbose_name='Kara punktowa'),
        ),
    ]
