# Generated by Django 3.2.6 on 2021-10-06 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zawody', '0002_sedzia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sedzia',
            options={'verbose_name_plural': 'Sędziowie'},
        ),
        migrations.AlterModelOptions(
            name='zawody',
            options={'verbose_name_plural': 'Zawody'},
        ),
    ]
