# Generated by Django 3.2.3 on 2021-11-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zawody', '0003_auto_20211006_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='sedzia',
            name='liczba_strzalow',
            field=models.IntegerField(default=10),
        ),
    ]
