# Generated by Django 3.2.3 on 2021-11-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zawody', '0004_sedzia_liczba_strzalow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sedzia',
            name='liczba_strzalow',
        ),
        migrations.AddField(
            model_name='zawody',
            name='liczba_strzalow',
            field=models.IntegerField(default=10),
        ),
    ]
