# Generated by Django 3.2.9 on 2022-01-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zawody', '0007_turniej_rejestracja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turniej',
            name='rejestracja',
            field=models.BooleanField(verbose_name='Rejestracja'),
        ),
    ]
