# Generated by Django 3.2.9 on 2022-04-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zawody', '0009_auto_20220223_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='zawody',
            name='oplata_amunicja',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='zawody',
            name='oplata_bron',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='zawody',
            name='oplata_konkurencja',
            field=models.FloatField(default=0),
        ),
    ]
